
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: sprint2
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  api:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
